name: return-dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        uses: firmanrosid/experiment/test@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch an action and get the run ID and URL
        uses: codex-/return-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: ${{ github.ref }}
          repo: experiment
          owner: firmanrosid
          workflow: test-deploy.yml
          workflow_timeout_seconds: 90 # Default: 300

      - name: Send report
        run: |
          echo "Send report"
