name: send-report

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "distinct_id"
        required: true
      run_id:
        description: "run_id"
        required: true

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/github-script@v7.0.1
        continue-on-error: true
        env:
          ARTIFACT_NAME: report-cp
          ARTIFACT_FILENAME: report-cp.zip
        with:
          script: |
            const script = require('./download-artifact/index.js')
            await script({github, context, core})
      - name: Run bash script
        run: ls -la
      - name: Run id
        run: |
          echo ${{ github.event.inputs.distinct_id }}
          echo ${{ github.event.inputs.run_id }}
