name: send-report

on:
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          ARTIFACT_NAME: report-cp
          ARTIFACT_FILENAME: report-cp.zip
        with:
          script: |
            const script = require('./download-artifact/index.js')
            await script({github, context, core})
      - run: ls -la
