name: build-and-deploy-gh-pages

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Run Test
        uses: firmanrosid/experiment/test@master

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Build and Deploy Pages
        uses: firmanrosid/experiment/build-and-deploy-pages@master
        with:
          ref: gh-pages
          source: ./
          destination: ./_site

  report:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: |
            Hello, Slack!
            Status: ${{ needs.test.outputs.status }}
            Message: ${{ needs.test.outputs.message }}
